version: "2"
services:
    mkdocs-jsf:
        build: ./docs
        image: challisa/mkdocs-jsf
        container_name: mkdocs-jsf
        ports:
            - "8000:8000"
        volumes:
            - .:/docs
        entrypoint: mkdocs serve --dev-addr 0.0.0.0:8000
